name: Pull Request
on:
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies and build 🔧
        run: yarn install --frozen-lockfile && yarn build
      - name: Run tests
        run: yarn test
