name: Test and Publish to NPM
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: yarn install --frozen-lockfile && yarn build
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: .
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Test
        run: yarn test
      
